# docker-compose.yml
version: '3.8'

services:
  frontend:
    depends_on:
      - app
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: easytravel_frontend
    ports:
      - "3000:3000"
    environment:
      # на клиенте будем дергать http://localhost:8000
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: [ "pnpm", "run", "dev" ]
    restart: always


  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_USER: emil
      DATABASE_PASSWORD: emilgan12
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: fastupdb
    volumes:
      - ./Backend:/usr/src/app
      - ./DLS:/usr/src/DLS
    restart: always

  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: emil
      POSTGRES_PASSWORD: emilgan12
      POSTGRES_DB: fastupdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: