"""Refresh Token

Revision ID: 9ad17b651a63
Revises: 
Create Date: 2025-06-28 15:17:20.883031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad17b651a63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('about_me', sa.String(length=200), nullable=False),
    sa.Column('interests', sa.ARRAY(sa.Enum('museums', 'art', 'history', 'architecture', 'nature', 'parks', 'cafes', 'restaurants', 'shopping', 'sports', 'active', 'recreation', 'nightlife', 'local', 'cuisine', 'photography', 'quiet', 'places', name='interests_enum')), nullable=False),
    sa.Column('additional_interests', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('additional_interests'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
